theme: jekyll-theme-slate
title: GitHub pages template
description: A simple template based on minimal jekyll theme
show_downloads: True
navigation:
  - title: Home
    url: /

  - title: 近期工作計畫
    url: todo
  
  - title: 產品
    url: product
  
  - title: 產品資訊分析表(手機查看)
    url: product_intro
  
    - title: 產品資訊分析表(電腦查看)
    url: product_swot
    
  - title: WebAPP項目計畫
    url: plan
    
  - title: 規格
    url: spec
    
  - title: 文檔
    url: docs
    
    
    
    
